name: Deploy Fastyshop Frontend to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm build

      - name: Clean remote dist folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "🧹 Очистка старых файлов dist/ на сервере..."
            rm -rf /home/deploy/apps/fastyshop-client/dist/*

      - name: Copy build to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "dist/*"
          target: "/home/deploy/apps/fastyshop-client"
          overwrite: true

      - name: Fix permissions on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "🔧 Установка владельца и прав на dist/"
            sudo chown -R www-data:www-data /home/deploy/apps/fastyshop-client/dist
            sudo chmod -R 755 /home/deploy/apps/fastyshop-client/dist
